<?php
if (is_file(__DIR__ . '/../../../framework/includes/libraries/AlibabaOSS/autoload.php')) {
    require_once __DIR__ . '/../../../framework/includes/libraries/AlibabaOSS/autoload.php';
}

use OSS\OssClient;
use OSS\Core\OssException;
use OSS\Core\OssUtil;

class ScoringConf
{
    //PERUSAHAAN
    const SCORING_CARA_PENDAFTARAN = 1;
    const SCORING_TAHUN_BERDIRI = 2;
    const SCORING_STATUS_TEMPAT_USAHA = 3;
    const SCORING_JUMLAH_KARYAWAN = 4;
    const SCORING_KANTOR_CABANG = 5;
    const SCORING_LAMA_USAHA = 6;
    //KEKAYAAN
    const SCORING_ASET_USAHA = 7;
    const SCORING_KEPEMILIKAN_SAHAM = 8;
    const SCORING_REKENING_BANK = 9;
    //PEKERJAAN
    const SCORING_JUMLAH_PROYEK = 10;
    const SCORING_LOKASI_PROYEK = 11;
    const SCORING_PENGALAMAN_KERJA = 12;
    //PENDAPATAN
    const SCORING_SUMBER_PENDAPATAN = 13;
    const SCORING_TOTAL_INCOME_PERBULAN = 14;
    const SCORING_DISPOSINLE_INCOME = 15;
    const SCORING_TAKE_HOME_PAY = 16;
    //JAMINAN
    const SCORING_JENIS_JAMINAN = 17;
    const SCORING_JAMINAN_RUMAH_TANAH_MOBIL = 18;
    const SCORING_JAMINAN_PERUSAHAAN = 19;
    const SCORING_KEPEMILIKAN_RUMAH = 20;
    const SCORING_LOKASI_JAMINAN_RUMAH = 21;

    //INDIVIDU
    //PRIBADI
    const SCORING_INDIVIDU_CARA_PENDAFTARAN = 1;
    const SCORING_INDIVIDU_USIA = 2;
    const SCORING_INDIVIDU_STATUS_PERKAWINAN = 3;
    const SCORING_INDIVIDU_JUMLAH_ANAK = 4;
    const SCORING_INDIVIDU_PENDIDIKAN = 5;
    const SCORING_INDIVIDU_LAMA_TINGGAL = 6;
    //KEKAYAAN
    const SCORING_INDIVIDU_ASET_USAHA = 7;
    const SCORING_INDIVIDU_KEPEMILIKAN_MOBIL = 8;
    const SCORING_INDIVIDU_REKENING_BANK = 9;
    //PEKERJAAN
    const SCORING_INDIVIDU_KARYAWAN = 10;
    const SCORING_INDIVIDU_WIRASWASTA = 11;
    const SCORING_INDIVIDU_POSISI = 12;
    const SCORING_INDIVIDU_PENGALAMAN_KERJA = 13;
    //PENDAPATAN
    const SCORING_INDIVIDU_SUMBER_PENDAPATAN = 14;
    const SCORING_INDIVIDU_TOTAL_INCOME_PERBULAN = 15;
    const SCORING_INDIVIDU_DISPOSINLE_INCOME = 16;
    const SCORING_INDIVIDU_TAKE_HOME_PAY = 17;
    //JAMINAN
    const SCORING_INDIVIDU_JENIS_JAMINAN = 18;
    const SCORING_INDIVIDU_JAMINAN_RUMAH_TANAH_MOBIL = 19;
    const SCORING_INDIVIDU_JAMINAN_PERUSAHAAN = 20;
    const SCORING_INDIVIDU_KEPEMILIKAN_RUMAH = 21;
    const SCORING_INDIVIDU_LOKASI_JAMINAN_RUMAH = 22;

}